### ISSUE TITLE
GEOSX compile fail because of mssing umpire directory.

### ISSUE THREAD

**Issue by lijun1234** [GEOSX/thirdPartyLibs#149]
Hi There,

Follow [the instruction](https://geosx-geosx.readthedocs-hosted.com/en/latest/docs/sphinx/QuickStart.html#download) to finish the third party build successfully. I ran config-build.py to generate GEOSX build folder but failed with the error about umpire, Lines between 206 and 220 in "GEOSX/src/cmake/thirdparty/SetupGeosxThirdParty.cmake" show Umpire is a required 3rd party lib. 
However there is no umpire directory under "thirdPartyLibs/install-<platform>-release". There is no umpire tar file under thirdPartyLibs/tplMirror either. 
Could someone take a look at this issue?

Regards.

**Comment by klevzoff** [comment]
Hi @lijun1234 ,

Umpire is normally built and installed automatically as a dependency of CHAI and located under the same path. You can check if `libumpire.a` is indeed found under `thirdPartyLibs/install--release/chai/lib`.

Depending on how you configure your GEOSX build:
  * If you only specify `GEOSX_TPL_DIR=/path/to/thirdPartyLibs/install--release`, make sure you `include(/path/to/GEOSX/host-configs/tpls.cmake)` afterwards in your host-config. That should set all the paths correctly.
  * If you specify each TPL path separately, then just setting CMake variable `UMPIRE_DIR=/path/to/thirdPartyLibs/install--release/chai` should be sufficient.

If the error persists, could you please post the entire CMake output, including the error message?

**Comment by lijun1234** [comment]
Hi @klevzoff,

Thank you for the quick responding. I use the second method. 

As you pointed, after setting UMPIRE_DIR same as CHAI_DIR, the build folder can be successfully created. Make and make install also pass. Now I can run geosx binary file.  Gave this project a star since I do see awsome developer behind.
