### ISSUE TITLE
Merge bugfix/klevzoff/fix-mathpresso-apple into master

### ISSUE THREAD

**Issue by MatthiasCremon** [GEOSX/thirdPartyLibs#15]
Merging Sergey's fix for Mathpresso would allow mac users to compile the TPLs without checking out this branch.

I'm not sure if there is a compatibility issue with master though, I don't see a pull request for that branch.

**Comment by klevzoff** [comment]
Randy has already merged it into master

**Comment by MatthiasCremon** [comment]
@klevzoff I just saw the commit from yesterday! My bad.
