### ISSUE TITLE
failed to linking CXX shared library libkokkoskernels.so

### ISSUE THREAD

**Issue by tab881** [GEOSX/thirdPartyLibs#160]
When I compile thirdPartyLibs, I met following issues:

[ 44%] Linking CXX shared library libteuchoskokkoscompat.so
[ 44%] Built target teuchoskokkoscompat
[ 44%] Linking CXX shared library libkokkoskernels.so
/usr/bin/ld: /usr/local/lib/libblas.a(sgemv.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libblas.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
packages/kokkos-kernels/src/CMakeFiles/kokkoskernels.dir/build.make:5031: recipe for target 'packages/kokkos-kernels/src/libkokkoskernels.so.12.18.1' failed
make[5]: *** [packages/kokkos-kernels/src/libkokkoskernels.so.12.18.1] Error 1
CMakeFiles/Makefile2:2810: recipe for target 'packages/kokkos-kernels/src/CMakeFiles/kokkoskernels.dir/all' failed
make[4]: *** [packages/kokkos-kernels/src/CMakeFiles/kokkoskernels.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
[ 44%] Linking CXX shared library libteuchoscomm.so
[ 44%] Built target teuchoscomm
Makefile:165: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/trilinos.dir/build.make:85: recipe for target 'trilinos/src/trilinos-stamp/trilinos-build' failed
make[2]: *** [trilinos/src/trilinos-stamp/trilinos-build] Error 2
CMakeFiles/Makefile2:809: recipe for target 'CMakeFiles/trilinos.dir/all' failed
make[1]: *** [CMakeFiles/trilinos.dir/all] Error 2
Makefile: 100: recipe for target 'all' failed
make: *** [all] Error 2

My configuration:
ubuntu-16.04
gcc/g++ -8.4.0
gfortran -5.5.0
openmpi-4.1.1
blas-3.10.0
lapack-3.10.0

**Comment by klevzoff** [comment]
Hi @tab881 , 

If you've built BLAS manually from source, you may need to rebuild it with `-fPIC` added to compiler flags (most likely `FCFLAGS`) and reinstall. If it was installed with a system package manager, I'd suggest making sure both `libblas-dev` and `libblas3` packages are installed (the latter provides shared library that should not have any linking problems). 

Let us know if this helps.

**Comment by tab881** [comment]
Sorry for the late response. I have successfully installed all the packages based on the solution from this links: https://stackoverflow.com/questions/45691778/cdt-using-lib-a-relocation-r-x86-64-32s-against-symbol-can-not-be-used

Thanks!
