### ISSUE TITLE
Careful, openMPI 4.0 is not compatible with the HDF5 version in the tpl 

### ISSUE THREAD

**Issue by AntoineMazuyer** [GEOSX/thirdPartyLibs#26]
https://github.com/open-mpi/ompi/issues/6116

**Comment by rrsettgast** [comment]
@corbett5 @AntoineMazuyer was this resolved?

**Comment by AntoineMazuyer** [comment]
Well I just check on my rolling release distro, I have OpenMPI 4.0.1 installed and I have no problem.

**Comment by CusiniM** [comment]
Interesting... I built an older OpenMPI and I do not get the error about non existing functions any more but with the newer one I definitely do...
